<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\TenantModule;
use App\Enums\TenantStatus;
use App\Enums\TenantType;
use App\Models\Tenant;
use App\Models\User;
use App\Services\SubdomainGenerator;
use Illuminate\Database\Seeder;

/**
 * Central database seeder.
 *
 * Seeds the central (super-admin) database and provisions sample tenants
 * for local development.  Run via:
 *   php artisan db:seed            (additive — safe to re-run)
 *   php artisan migrate:fresh --seed
 *
 * Provisioning sample tenants here triggers the full stancl/tenancy event
 * pipeline:  CreateDatabase → MigrateDatabase → SeedDatabase
 * (TenantDatabaseSeeder), which populates each tenant's own PostgreSQL
 * database with 13 dev users, EDMS seed data, and Spatie roles.
 *
 * This seeder MUST NOT call EDMS seeders directly — those tables exist only
 * inside individual tenant databases, never in the central database.
 */
class DatabaseSeeder extends Seeder
{
    public function __construct(private readonly SubdomainGenerator $subdomainGenerator) {}

    public function run(): void
    {
        $this->seedSuperAdmin();
        $this->seedSampleTenants();
    }

    // ── Central super-admin ───────────────────────────────────────────────────

    private function seedSuperAdmin(): void
    {
        // is_super_admin = true grants an unconditional Gate::before() bypass
        // in AppServiceProvider — this user exists ONLY in the central DB.
        User::updateOrCreate(
            ['email' => 'superadmin@nectarmetrics.com.ng'],
            [
                'name'              => 'Super Administrator',
                'user_name'         => 'superadmin',
                'phone'             => '08000000001',
                'email_verified_at' => now(),
                'password'          => bcrypt('passw0rd!'),
                'is_super_admin'    => true,
                'is_admin'          => true,
                'is_active'         => true,
            ]
        );
    }

    // ── Sample tenants (local dev only) ──────────────────────────────────────

    /**
     * Provision two representative tenants for local development.
     *
     * Each call is idempotent: if a tenant with the same short_name already
     * exists the row is skipped.  Domains are generated by SubdomainGenerator
     * so the output matches what TenantController::store() would produce.
     *
     * Local FQDNs — add to /etc/hosts:
     *   127.0.0.1  finance.localhost
     *   127.0.0.1  hra.localhost
     */
    private function seedSampleTenants(): void
    {
        $tenants = [
            [
                'organization_name' => 'Federal Ministry of Finance',
                'short_name'        => 'finance',
                'admin_email'       => 'admin@finance.gov.ng',
                'tenant_type'       => TenantType::SECRETARIAT,
            ],
            [
                'organization_name' => 'National Human Resources Agency',
                'short_name'        => 'hra',
                'admin_email'       => 'admin@hra.gov.ng',
                'tenant_type'       => TenantType::AGENCY,
            ],
        ];

        foreach ($tenants as $data) {
            // Idempotency guard — skip if already provisioned.
            if (Tenant::where('short_name', $data['short_name'])->exists()) {
                $this->command->line("  Tenant [{$data['short_name']}] already exists — skipped.");
                continue;
            }

            $this->command->line("  Provisioning tenant [{$data['short_name']}]…");

            // Tenant::create() fires TenantCreated → CreateDatabase
            // → MigrateDatabase → SeedDatabase(TenantDatabaseSeeder).
            $tenant = Tenant::create([
                'organization_name' => $data['organization_name'],
                'short_name'        => $data['short_name'],
                'admin_email'       => $data['admin_email'],
                'tenant_type'       => $data['tenant_type'],
                'status'            => TenantStatus::PENDING,
                'settings'          => ['modules' => TenantModule::defaults()],
            ]);

            // Attach the primary domain using the same generator the
            // controller uses — ensures FQDN format is env-consistent.
            $fqdn = $this->subdomainGenerator->generate($data['short_name']);
            $tenant->domains()->create(['domain' => $fqdn]);

            // Activate immediately — provisioning is synchronous.
            $tenant->transitionStatus(TenantStatus::ACTIVE);

            $this->command->info("  Tenant [{$data['short_name']}] provisioned at {$fqdn} ✓");
        }
    }
}
