<?php

declare(strict_types=1);

namespace App\Http\Requests;

use App\Enums\TenantModule;
use App\Enums\TenantType;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rules\Enum;
use Illuminate\Validation\Validator;

class StoreTenantRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('create', \App\Models\Tenant::class) ?? false;
    }

    public function rules(): array
    {
        return [
            // ── Idempotency key ────────────────────────────────────────────
            // Generated by TenantController::create() and embedded as a hidden
            // field.  Validated here to ensure the token is structurally valid;
            // the session-match check lives in after() below.
            '_provision_key'    => ['required', 'string', 'uuid'],

            // ── Tenant fields ──────────────────────────────────────────────
            // NOTE: 'domain' is intentionally absent — the subdomain is
            // auto-generated by SubdomainGenerator::generate(short_name)
            // inside TenantController::store().  Admins can add custom
            // domains after provisioning via the Domain Management panel.
            'organization_name' => ['required', 'string', 'max:255'],

            // short_name is the slug seed for the auto-generated subdomain.
            // Rules: 2–30 chars, lowercase alphanumeric + internal hyphens,
            // must start and end with a letter or digit, globally unique.
            'short_name'        => [
                'required',
                'string',
                'min:2',
                'max:30',
                'regex:/^[a-z0-9][a-z0-9-]*[a-z0-9]$/',
                'unique:tenants,short_name',
            ],

            'admin_email'       => ['required', 'email', 'max:255'],
            'tenant_type'       => ['required', new Enum(TenantType::class)],
            'notes'             => ['nullable', 'string', 'max:1000'],

            // ── Module access ──────────────────────────────────────────────
            'modules'           => ['nullable', 'array'],
            'modules.*'         => ['string', 'in:' . implode(',', TenantModule::values())],
        ];
    }

    /**
     * After-hook: cross-field and session-based validation that cannot live
     * in rules() because it requires access to the session.
     *
     * Validates that the submitted idempotency key matches the server-side
     * session token.  A mismatch means either:
     *   (a) the form was already submitted successfully (back-button replay), or
     *   (b) the session expired while the user was filling in the form.
     *
     * In both cases we reject the submission here so TenantController::store()
     * never runs — the controller's explicit key-consumption guard is a
     * belt-and-suspenders second check.
     *
     * @return array<\Closure>
     */
    public function after(): array
    {
        return [
            function (Validator $validator): void {
                $submitted = $this->input('_provision_key');
                $expected  = session('tenant_provision_key');

                if (! $expected || $submitted !== $expected) {
                    $validator->errors()->add(
                        '_provision_key',
                        'This form was already submitted or your session expired. Please use the form below to provision a new tenant.'
                    );
                }
            },
        ];
    }

    public function messages(): array
    {
        return [
            '_provision_key.required' => 'The provisioning form token is missing. Please reload the page.',
            '_provision_key.uuid'     => 'The provisioning form token is malformed. Please reload the page.',
            'short_name.regex'        => 'Short name may only contain lowercase letters, numbers, and hyphens, and must start and end with a letter or digit.',
            'short_name.unique'       => 'This short name is already in use by another tenant.',
            'modules.*.in'            => 'One or more selected modules are invalid.',
        ];
    }
}
