<?php

declare(strict_types=1);

namespace App\Http\Requests;

use App\Enums\TenantModule;
use App\Enums\TenantType;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rules\Enum;
use Illuminate\Validation\Validator;

class StoreTenantRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('create', \App\Models\Tenant::class) ?? false;
    }

    public function rules(): array
    {
        return [
            // ── Idempotency key ────────────────────────────────────────────
            // Generated by TenantController::create() and embedded as a hidden
            // field.  Validated here to ensure the token is structurally valid;
            // the session-match check lives in after() below.
            '_provision_key'    => ['required', 'string', 'uuid'],

            // ── Tenant fields ──────────────────────────────────────────────
            'organization_name' => ['required', 'string', 'max:255'],
            'admin_email'       => ['required', 'email', 'max:255'],
            'tenant_type'       => ['required', new Enum(TenantType::class)],
            'domain'            => [
                'required', 'string', 'max:255',
                'regex:/^[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?(\.[a-z0-9\-]{2,})+$/',
                'unique:domains,domain',
            ],
            'notes'             => ['nullable', 'string', 'max:1000'],

            // ── Module access ──────────────────────────────────────────────
            'modules'           => ['nullable', 'array'],
            'modules.*'         => ['string', 'in:' . implode(',', TenantModule::values())],
        ];
    }

    /**
     * After-hook: cross-field and session-based validation that cannot live
     * in rules() because it requires access to the session.
     *
     * Validates that the submitted idempotency key matches the server-side
     * session token.  A mismatch means either:
     *   (a) the form was already submitted successfully (back-button replay), or
     *   (b) the session expired while the user was filling in the form.
     *
     * In both cases we reject the submission here so TenantController::store()
     * never runs — the controller's explicit key-consumption guard is a
     * belt-and-suspenders second check.
     *
     * @return array<\Closure>
     */
    public function after(): array
    {
        return [
            function (Validator $validator): void {
                $submitted = $this->input('_provision_key');
                $expected  = session('tenant_provision_key');

                if (! $expected || $submitted !== $expected) {
                    $validator->errors()->add(
                        '_provision_key',
                        'This form was already submitted or your session expired. Please use the form below to provision a new tenant.'
                    );
                }
            },
        ];
    }

    public function messages(): array
    {
        return [
            '_provision_key.required' => 'The provisioning form token is missing. Please reload the page.',
            '_provision_key.uuid'     => 'The provisioning form token is malformed. Please reload the page.',
            'domain.regex'            => 'Domain must be a valid fully-qualified hostname (e.g. ict.youredms.com).',
            'domain.unique'           => 'This domain is already assigned to another tenant.',
            'modules.*.in'            => 'One or more selected modules are invalid.',
        ];
    }
}
